const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id);const scoreEl=$('score'),timeEl=$('time'),levelEl=$('level'),bestEl=$('best'),stateLabel=$('stateLabel');
const overlays=[$('startOverlay'),$('pauseOverlay'),$('gameOverOverlay')];const keys={left:false,right:false};
const STATES=Object.freeze({START:'START',PLAYING:'PLAYING',PAUSED:'PAUSED',WON:'WON',LOST:'LOST'});let state=STATES.START,raf=null,last=0,elapsed=0,score=0,level=1,spawnTimer=.25,toastTimer=0,obstacles=[],particles=[],stars=[];let best=Number(localStorage.getItem('neonDodgeBest')||0);const player={x:0,y:0,w:34,h:48,speed:390};
let soundEnabled=localStorage.getItem('neonDodgeSound')!=='off';
let reducedMotion=localStorage.getItem('neonDodgeReducedMotion')==='on';
let audioCtx=null;
function announce(m){$('liveStatus').textContent=m}
function initAudio(){if(!soundEnabled)return;if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
function beep(f=440,d=.08,type='sine',v=.035){if(!soundEnabled)return;initAudio();if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}
function feedback(k){if(k==='start'){beep(520,.07,'triangle');setTimeout(()=>beep(740,.09,'triangle'),70)}if(k==='pause')beep(260,.1);if(k==='resume')beep(520,.08);if(k==='level'){beep(620,.07,'square');setTimeout(()=>beep(880,.1,'square'),80)}if(k==='hit')beep(120,.22,'sawtooth',.045);if(k==='win'){beep(660,.08,'triangle');setTimeout(()=>beep(880,.08,'triangle'),90);setTimeout(()=>beep(1040,.13,'triangle'),180)}}
function applyAccessibility(){document.body.classList.toggle('reduced-motion',reducedMotion);$('soundToggle').checked=soundEnabled;$('motionToggle').checked=reducedMotion}

function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);player.y=r.height-88;if(!player.x)player.x=r.width/2;stars=Array.from({length:Math.max(50,Math.floor(r.width/10))},()=>({x:Math.random()*r.width,y:Math.random()*r.height,size:Math.random()*1.7+.3,speed:Math.random()*20+8}))}addEventListener('resize',resize);
function setState(next){const allowed={[STATES.START]:[STATES.PLAYING],[STATES.PLAYING]:[STATES.PAUSED,STATES.WON,STATES.LOST],[STATES.PAUSED]:[STATES.PLAYING,STATES.START],[STATES.WON]:[STATES.PLAYING],[STATES.LOST]:[STATES.PLAYING]};if(!allowed[state].includes(next))return false;state=next;stateLabel.textContent=state;return true}
function hud(){scoreEl.textContent=String(score).padStart(5,'0');timeEl.textContent=elapsed.toFixed(1).padStart(4,'0');levelEl.textContent=level;bestEl.textContent=String(best).padStart(5,'0')}
function resetRun(){const w=canvas.clientWidth,h=canvas.clientHeight;player.x=w/2;player.y=h-88;elapsed=0;score=0;level=1;spawnTimer=.25;toastTimer=0;obstacles=[];particles=[];keys.left=keys.right=false;hud()}
function hide(){overlays.forEach(x=>x.classList.add('hidden'))}
function startRun(){if(![STATES.START,STATES.PAUSED,STATES.WON,STATES.LOST].includes(state))return;if(!setState(STATES.PLAYING))return;resetRun();hide();initAudio();feedback('start');announce('Game started. Use left and right controls to dodge obstacles.');cancelAnimationFrame(raf);last=performance.now();raf=requestAnimationFrame(loop)}
function pauseRun(){if(state!==STATES.PLAYING)return;if(!setState(STATES.PAUSED))return;feedback('pause');announce('Game paused.');cancelAnimationFrame(raf);raf=null;$('pauseOverlay').classList.remove('hidden')}
function resumeRun(){if(state!==STATES.PAUSED)return;if(!setState(STATES.PLAYING))return;feedback('resume');announce('Game resumed.');$('pauseOverlay').classList.add('hidden');last=performance.now();raf=requestAnimationFrame(loop)}
function restartRun(){if(![STATES.PAUSED,STATES.WON,STATES.LOST].includes(state))return;startRun()}
function endRun(won){if(state!==STATES.PLAYING)return;setState(won?STATES.WON:STATES.LOST);cancelAnimationFrame(raf);raf=null;if(score>best){best=score;localStorage.setItem('neonDodgeBest',best)}if(won){feedback('win');announce('You survived 60 seconds and won the run.')}else{feedback('hit');announce('Game over. You collided with an obstacle.')}$('resultEyebrow').textContent=won?'TARGET COMPLETE':'RUN COMPLETE';$('resultTitle').textContent=won?'YOU SURVIVED':'GAME OVER';$('resultText').textContent=won?'60 seconds complete. You cleared the final target!':'You collided with an obstacle. Restart and try a higher score.';$('finalScore').textContent=String(score).padStart(5,'0');$('finalTime').textContent=elapsed.toFixed(1)+'s';$('finalLevel').textContent=level;$('finalBest').textContent=String(best).padStart(5,'0');$('gameOverOverlay').classList.remove('hidden');hud();draw(0)}
function spawn(){const w=canvas.clientWidth,size=24+Math.random()*30;obstacles.push({x:size+Math.random()*(w-size*2),y:-size,size,speed:165+level*28+elapsed*2.7+Math.random()*70,angle:Math.random()*Math.PI,spin:(Math.random()-.5)*3})}
function hit(o){return Math.abs(o.x-player.x)<(o.size+player.w)*.45&&Math.abs(o.y-player.y)<(o.size+player.h)*.45}
function explode(x,y){if(reducedMotion)return;for(let i=0;i<38;i++){const a=Math.random()*Math.PI*2,s=60+Math.random()*260;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.5+Math.random()*.6})}}
function update(dt){const w=canvas.clientWidth,move=(keys.right?1:0)-(keys.left?1:0);player.x=Math.max(24,Math.min(w-24,player.x+move*player.speed*dt));elapsed+=dt;score=Math.floor(elapsed*100);const next=Math.min(5,Math.floor(elapsed/12)+1);if(next>level){level=next;$('levelToastNumber').textContent=level;$('levelToast').classList.remove('hidden');toastTimer=1.25;feedback('level');announce('Level '+level+'. Difficulty increased.')}const interval=Math.max(.26,.92-level*.11-elapsed*.004);spawnTimer-=dt;if(spawnTimer<=0){spawn();spawnTimer=interval}obstacles.forEach(o=>{o.y+=o.speed*dt;o.angle+=o.spin*dt});obstacles=obstacles.filter(o=>o.y<canvas.clientHeight+80);for(const o of obstacles)if(hit(o)){explode(player.x,player.y);endRun(false);return}if(toastTimer>0&&(toastTimer-=dt)<=0)$('levelToast').classList.add('hidden');if(elapsed>=60)endRun(true);hud()}
function background(dt){const w=canvas.clientWidth,h=canvas.clientHeight,g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#07031a');g.addColorStop(1,'#010107');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);stars.forEach(s=>{s.y+=s.speed*dt;if(s.y>h){s.y=-3;s.x=Math.random()*w}ctx.fillStyle='rgba(150,125,255,.5)';ctx.fillRect(s.x,s.y,s.size,s.size)});const hz=h*.56;ctx.strokeStyle='rgba(105,75,200,.18)';for(let y=hz;y<h+100;y+=38){const p=(y-hz)/(h-hz),yy=y+p*p*40;ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(w,yy);ctx.stroke()}for(let x=-w;x<=w*2;x+=70){ctx.beginPath();ctx.moveTo(w/2,hz);ctx.lineTo(x,h);ctx.stroke()}}
function drawPlayer(){ctx.save();ctx.translate(player.x,player.y);ctx.shadowBlur=28;ctx.shadowColor='#5ffcff';ctx.beginPath();ctx.moveTo(0,-24);ctx.lineTo(17,24);ctx.lineTo(0,16);ctx.lineTo(-17,24);ctx.closePath();ctx.fillStyle='#5ffcff';ctx.fill();ctx.shadowBlur=12;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,-5,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(255,79,216,.8)';ctx.beginPath();ctx.moveTo(-8,24);ctx.lineTo(0,44);ctx.lineTo(8,24);ctx.closePath();ctx.fill();ctx.restore()}
function drawObstacle(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.angle);ctx.shadowBlur=22;ctx.shadowColor='#ff4fd8';ctx.strokeStyle='#ff4fd8';ctx.fillStyle='rgba(255,79,216,.15)';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3,r=o.size*(i%2?.72:1),x=Math.cos(a)*r,y=Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
function draw(dt){background(dt);obstacles.forEach(drawObstacle);drawPlayer();particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;ctx.globalAlpha=Math.max(0,p.life/.8);ctx.fillStyle='#5ffcff';ctx.fillRect(p.x,p.y,3,3)});particles=particles.filter(p=>p.life>0);ctx.globalAlpha=1}
function loop(now){if(state!==STATES.PLAYING)return;const dt=Math.min((now-last)/1000,.04);last=now;update(dt);draw(dt);if(state===STATES.PLAYING)raf=requestAnimationFrame(loop)}
function setKey(k,v){if(state===STATES.PLAYING)keys[k]=v}
addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key)){e.preventDefault();setKey('left',true)}if(['ArrowRight','d','D'].includes(e.key)){e.preventDefault();setKey('right',true)}if(['p','P','Escape'].includes(e.key)){e.preventDefault();state===STATES.PLAYING?pauseRun():state===STATES.PAUSED&&resumeRun()}if(e.key===' '){e.preventDefault();if(state===STATES.START||state===STATES.WON||state===STATES.LOST)startRun()}});addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.left=false;if(['ArrowRight','d','D'].includes(e.key))keys.right=false});
function hold(id,key){const b=$(id),on=e=>{e.preventDefault();setKey(key,true)},off=e=>{e.preventDefault();keys[key]=false};['pointerdown','touchstart'].forEach(x=>b.addEventListener(x,on,{passive:false}));['pointerup','pointercancel','pointerleave','touchend'].forEach(x=>b.addEventListener(x,off,{passive:false}))}hold('leftBtn','left');hold('rightBtn','right');
$('startBtn').onclick=()=>state===STATES.START&&startRun();$('resumeBtn').onclick=()=>state===STATES.PAUSED&&resumeRun();$('pauseRestartBtn').onclick=()=>state===STATES.PAUSED&&restartRun();$('restartBtn').onclick=()=>[STATES.WON,STATES.LOST].includes(state)&&restartRun();
$('settingsBtn').onclick=()=>{$('settingsOverlay').classList.remove('hidden');$('soundToggle').focus();announce('Settings opened.')};
$('closeSettingsBtn').onclick=()=>{$('settingsOverlay').classList.add('hidden');$('settingsBtn').focus();announce('Settings closed.')};
$('soundToggle').onchange=e=>{soundEnabled=e.target.checked;localStorage.setItem('neonDodgeSound',soundEnabled?'on':'off');if(soundEnabled){initAudio();beep(720,.08,'triangle')}announce(soundEnabled?'Sound effects enabled.':'Sound effects muted.')};
$('motionToggle').onchange=e=>{reducedMotion=e.target.checked;localStorage.setItem('neonDodgeReducedMotion',reducedMotion?'on':'off');applyAccessibility();announce(reducedMotion?'Reduced motion enabled.':'Reduced motion disabled.')};
$('settingsOverlay').addEventListener('click',e=>{if(e.target===$('settingsOverlay'))$('closeSettingsBtn').click()});
applyAccessibility();
resize();hud();draw(0);
